### ISSUE TITLE
AttributeError 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by anthonyjb** [messagebird/python-rest-api#11]
Hi,

I'm intermittently getting the following error when sending SMS messages using the Python client:

https://app.getsentry.com/share/issue/38393239372e313531303139363139/

The reason for the error appears to be the format the Python code expects back at this point (https://app.getsentry.com/share/issue/38393239372e313531303139363139/):

```python
@recipients.setter
  def recipients(self, value):
    value['items'] = [Recipient().load(r) for r in value['items']]
    self._recipients = value
```

which differs from what the API returns (I've removed the real number but will happily share privately if that helps):

```python
{
    'items': {
        '1': {
            'recipient': xxxxxxxxxx, 
            'status': 'sent', 
            'statusDatetime': '2016-08-18T21:26:06+00:00'
        }
    }, 
    'totalCount': 1, 
    'totalDeliveredCount': 0, 
    'totalDeliveryFailedCount': 0, 
    'totalSentCount': 1
}
```

So basically this line appears to expect a list of dictionaries back...

```python
value['items'] = [Recipient().load(r) for r in value['items']]
```

... but it's getting a dictionary or dictionaries with the key `1`, and the list comprehension here is simply sending through the key which isn't the dictionary expected by `load(r)`.

Since this doesn't always happen this seems most likely to be an error with the API, as in I can't see anywhere in the code where it would handle data in this structure received back from the API and for the most part this error doesn't occur when I send text messages. Also the API docs and example suggest items should be a list not a dictionary (https://developers.messagebird.com/docs/messaging#messaging-send).

A possible short-term hack I could try would be to patch the library to sniff the data type first, e.g:

```python
@recipients.setter
  def recipients(self, value):
    if isinstance(value['items'], dict):
        items = value['items']
        keys = sorted([int(k) for k in items.keys()])
        value['items'] = [Recipient().load(items[k]) for k in keys]
    else:
        value['items'] = [Recipient().load(r) for r in value['items']]
    self._recipients = value
```

...though if I'm honest I'd really prefer not to have to do this.

I'm using version 1.2.0 of your Python client library.

**Comment by samwierema** [comment]
@anthonyjb thanks for opening the issue. Our technical team is having a look at this today.

**Comment by samwierema** [comment]
@anthonyjb could you perhaps email me with sample data at sam@messagebird.com?

**Comment by samwierema** [comment]
@anthonyjb we were able to confirm and reproduce the issue, which is indeed present in our REST API. We've created a patch and have deployed this. Can you confirm that the issue has been resolved on your end?

**Comment by anthonyjb** [comment]
@samwierema thank you for the fast response to this - I'm currently out for a few hours but will attempt to recreate the error when I'm back and come back to you if I can reproduce the error.

**Comment by sygys** [comment]
i saw this post when looking for the error. 

It seems the error is back i get the samen error:

```
Logger: custom_components.hacs
Source: custom_components/hacs/base.py:488
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 27 augustus 2022 om 09:53:07 (2 occurrences)
Last logged: 27 augustus 2022 om 12:53:09

'str' object has no attribute 'items'
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 488, in async_github_api_method
    return await method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiogithubapi/namespaces/contents.py", line 62, in get
    response.data = GitHubContentsModel(response.data)
  File "/usr/local/lib/python3.10/site-packages/aiogithubapi/models/base.py", line 35, in __init__
    for key, value in self._raw_data.items():
AttributeError: 'str' object has no attribute 'items'
```

On toip of that this error at the same time:

```
Logger: custom_components.hacs
Source: custom_components/hacs/utils/queue_manager.py:71
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 27 augustus 2022 om 12:53:09 (1 occurrences)
Last logged: 27 augustus 2022 om 12:53:09

<QueueManager> 'str' object has no attribute 'items'
```

**Comment by nqkdev** [comment]
@sygys Looking at the stack trace, I see your error is unrelated to the messagebird/python-rest-api. Please create an issue here: https://github.com/hacs/integration/issues as shown in your error
